name: Deploy Supabase migrations to Production

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}
      CLIENT_ID: x
      CLIENT_SECRET: x

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - run: |
          supabase link --project-ref $PROJECT_ID
          supabase db push
